name: Lint, Format, and Test

on:
  workflow_call:
  workflow_dispatch:
  pull_request:

env:
    TEST_API_KEY: ${{ secrets.TEST_API_KEY }}
    TEST_APP_ID: ${{ secrets.TEST_APP_ID }}
    TEST_USER_ID: ${{ secrets.TEST_USER_ID }}
    TEST_USER_IDENTIFIER: ${{ secrets.TEST_USER_IDENTIFIER }}

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: npm i
      - name: Lint
        run: npm run lint:ci
  format:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: npm i
      - name: Format
        run: |
          if [[ $(npm run format:ci) ]]; then
            echo "Run 'npm run format' to format code."
            exit 1
          fi
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: npm i
      - name: Test
        run: npm run test
