name: Run Tests on PR

on: [pull_request]

env:
    TEST_API_KEY: ${{ secrets.TEST_API_KEY }}
    TEST_APP_ID: ${{ secrets.TEST_APP_ID }}
    TEST_AUTH_TOKEN: ${{ secrets.TEST_AUTH_TOKEN }}
    TEST_USER_ID: ${{ secrets.TEST_USER_ID }}
    TEST_USER_IDENTIFIER: ${{ secrets.TEST_USER_IDENTIFIER }}

jobs:
    publish:
        name: Run Tests on PR
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Install Dependencies
              run: npm i

            - name: ESLint Check
              run: npm run lint:ci

            - name: Beachball Check
              run: |
                  npm run beachball-check

            - name: Unit Test
              run: npm run test
