name: Run tests on deploy-production by backend-services

on:
    workflow_dispatch:

env:
    TEST_API_KEY: ${{ secrets.TEST_API_KEY }}
    TEST_APP_ID: ${{ secrets.TEST_APP_ID }}
    TEST_USER_ID: ${{ secrets.TEST_USER_ID }}
    TEST_USER_IDENTIFIER: ${{ secrets.TEST_USER_IDENTIFIER }}

jobs:
    test:
        name: Run Unit Tests
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Install Dependencies
              run: npm i

            - name: Unit Test
              run: npm run test
